#!/usr/bin/env bash

set -e

##############################################
#
# Build and push telegram-gas-tracker image
#
# Usage:
#   ./build.sh
#
##############################################
build() {
    docker build -t telegram-gas-tracker:v0.0.1 .

    docker tag telegram-gas-tracker:v0.0.1 700029131908.dkr.ecr.eu-central-1.amazonaws.com/telegram-gas-tracker:latest
    docker push 700029131908.dkr.ecr.eu-central-1.amazonaws.com/telegram-gas-tracker:latest
}

build
